[versions]
annotations = "25.0.0"
jupiter = "5.11.1"
junit-platform = "1.11.1"
mockserver = "5.15.0"
logback = "1.5.12"
gson = "2.11.0"

spotless = "6.25.0"
nexus  = "2.0.0"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
jupiter = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "jupiter" }
junitPlatform = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-platform" }
mockserverNetty = { group = "org.mock-server", name = "mockserver-netty", version.ref = "mockserver" }
mockserverClient = { group = "org.mock-server", name = "mockserver-client-java", version.ref = "mockserver" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
nexus = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus" }
